apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      name: app-pod
  template:
    metadata:
      labels:
        name: app-pod
    spec:
      containers:
      - name: app-c
        image: jaddusantoshkumar/eg:latest
        ports:
        - containerPort: 3000

